project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  sidebar:
    style: floating
    contents:
      - auto: "/*.ipynb"
      - section: Tutorials
        contents: tutorial/*
      - section: Live-Coding
        contents: Live-Coding/*
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Get Started"
        href: index.ipynb
      - text: "Tutorial"
        href: tutorial/lesson1-part1.html
      - text: "Blog"
        href: index.ipynb
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: bug
            href: https://github.com/nextric/Deep-Learning/issues
          - text: "Fast.ai Forum"
            icon: chat-right-text
            href: https://nextrick.freeflarum.com/
          - text: "FAQ"
            icon: question-circle
            href: getting_started.ipynb#faq
    right:
      - icon: github
        href: "https://github.com/nextrick/Deep-Learning"



metadata-files: [nbdev.yml]